### ISSUE TITLE
multi-ue problem roaming scenario

### ISSUE THREAD

**Issue by paaszti** [Borjis131/docker-open5gs#13]
I have an issue about using multi UEs. 
My docker-compose file:
```sh
  packetrusher:
    container_name: packetrusher
    image: "ghcr.io/borjis131/packetrusher:main"
    command: "--config /PacketRusher/config/packetrusher.yaml multi-ue -n 5 --tunnel --dedicatedGnb"
    networks:
      open5gs:
        aliases:
          - gnb.packetrusher.org
    configs:
      - source: packetrusher_config
        target: /PacketRusher/config/packetrusher.yaml
    privileged: true
    cap_add:
      - ALL
    depends_on:
      - v-amf
```
Logs from packetrusher:
```sh
time="2024-10-09T13:25:37Z" level=info msg="Selecting 10.33.33.12 for host amf.5gc.mnc070.mcc999.3gppnetwork.org as AMF's IP address"
time="2024-10-09T13:25:37Z" level=info msg="Selecting 10.33.33.19 for host gnb.packetrusher.org as gNodeB's N3/Data IP address"
time="2024-10-09T13:25:37Z" level=info msg="Selecting 10.33.33.19 for host gnb.packetrusher.org as gNodeB's N2/Control IP address"
time="2024-10-09T13:25:37Z" level=info msg="Loaded config at: /PacketRusher/config/packetrusher.yaml"
time="2024-10-09T13:25:37Z" level=info msg="PacketRusher version 1.0.1"
time="2024-10-09T13:25:37Z" level=info msg=---------------------------------------
time="2024-10-09T13:25:37Z" level=info msg="[TESTER] Starting test function: Testing registration of multiple UEs"
time="2024-10-09T13:25:37Z" level=info msg="[TESTER][UE] Number of UEs: 5"
time="2024-10-09T13:25:37Z" level=info msg="[TESTER][GNB] gNodeB control interface IP/Port: 10.33.33.19/38412~"
time="2024-10-09T13:25:37Z" level=info msg="[TESTER][GNB] gNodeB data interface IP/Port: 10.33.33.19/2152"
time="2024-10-09T13:25:37Z" level=info msg="[TESTER][AMF] AMF IP/Port: 10.33.33.12/38412"
time="2024-10-09T13:25:37Z" level=info msg=---------------------------------------
time="2024-10-09T13:25:37Z" level=info msg="[GNB] SCTP/NGAP service is running"
time="2024-10-09T13:25:37Z" level=info msg="[GNB] Initiating NG Setup Request"
time="2024-10-09T13:25:37Z" level=fatal msg="Error incannot assign requested address"
```
This time I have added UEs to the database  
Best regards

**Comment by Borjis131** [comment]
Hi @paaszti, I did not test this setup but I think I know the problem.

When you are using PacketRusher with the `multi-ue` option and using the `--tunnel` and `--dedicatedGnb` flags, PacketRusher tries to create a gNB per each UE you are giving on the `multi-ue` `-n`flag, in your case 5. For this PacketRusher grabs the IP that you gave it on the config file (e.g. 10.33.33.19) and uses it for the first gNB and then uses the next IP address (e.g. 10.33.33.20) for the next gNB, and so on.

So it is a bit tricky to configure this on Docker without creating multiple networks and even if you did that it would be a mess because PacketRusher is expecting to use the next IP address.

For this particular scenario that you need 5 UEs and PacketRusher will create 5 gNBs for them I would suggest to modify the docker-compose.yaml file and add 5 packetrusher containers each one with its own IP address and all. That way you will have the same effect on the network.

Hope this helps!

**Comment by Borjis131** [comment]
Hi @paaszti any news about this? Can I close the issue?

**Comment by paaszti** [comment]
I manually added one new container with UE and gNB
But I was wondering if it is possible to assign multiple UEs to one gNB?
Is it possible to add UE to local network without roaming?

**Comment by Borjis131** [comment]
@paaszti multiple UEs inside the same gNB only works if you use the options `multi-ue -n X` where X is the number of UEs that you want to create. But this only works with the control plane connection. For the user plane connection to work, you need to do the one gNB per UE as I told you.

And yes, it is possible. Take a look at the deployment `internal/packetrusher` that deployment is being used without roaming.
